version: '3.8'

services:
  mars:
    build: .
    container_name: mars-energy-controller
    restart: unless-stopped
    environment:
      - MQTT_BROKER_IP=192.168.178.6
      - MQTT_BROKER_PORT=1883
      - SMARTMETER_IP=192.168.178.53
      - SMARTMETER_PORT=12345
    networks:
      - host_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  host_network:
    driver: bridge
